name: Olymp
version: 1
author: Hyu
main: fr.hyu.olymp.Main
commands:
  olymp:
    description: Permet d'acceder à toutes les commandes du plugin Olymp.
  party:
    description: Permet de créer une partie avec ses ami(e)s.
  chatcolor:
    description: Affiche la liste des couleurs.
  setwarp:
    description: Permet de créer un nouveau warp
  warp:
    description: Permet de voir la liste des warps
  gms:
    description: met le joueur en mode survie
  gmc:
    description: met le joueur en mode créatif
  gma:
    description: met le joueur en mode aventure
  gmsp:
    description: met le joueur en mode spectateur
